# This is a basic workflow to help you get started with Actions

name: OpenWRT

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '*'

jobs:

  build_openwrt:

    name: Build OpenWrt and release
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          df -h
          
      - name: Git clone lede and plugins
        run: |
          git clone https://github.com/coolsnowwolf/lede
          git clone https://github.com/XinSSS/luci-app-vssr-plus lede/package/lean/luci-app-vssr-plus
          git clone -b master https://github.com/vernesong/OpenClash
          # git clone https://github.com/frainzy1477/luci-app-clash lede/package/lean/luci-app-clash
          cp -R OpenClash/luci-app-openclash lede/package/lean/luci-app-openclash
          cat feeds >> lede/feeds.conf.default
          
      - name: Update feeds
        run: |
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Generate configuration file
        run: |
          cd lede
          rm -f ./.config*
          touch ./.config
          cat ../seed.config > .config
          make defconfig

      
      - name: Make download
        run: |
          cd lede
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
          df -h
          
      - name: Compile firmware
        run: |
          cd lede
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
          
      - name: Prepare artifact
        run: find ./lede/bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload firmware
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_Firmware
          path: ./lede/bin/targets/
          
      - name: Upload ipk
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_IPK
          path: ./lede/bin/packages/
          
      - name: Upload config
        uses: actions/upload-artifact@master
        with:
          name: Config
          path: ./lede/.config
          
          
